export const dictonary = {
    ru: {
        messages: {
            required: () => "Обязательное поле.",
            after: () => "",
            alpha_dash: () => "",
            alpha_num: () => "",
            alpha_spaces: () => "",
            before: () => "",
            between: (field, params) => `Значение должно быть между ${params[0]}, ${params[1]}`,
            confirmed: () => "",
            credit_card: () => "",
            date_between: () => "",
            date_format: () => "",
            decimal: () => "",
            digits: () => "",
            dimensions: () => "",
            email: () => "",
            ext: () => "",
            image: () => "",
            included: () => "",
            integer: () => "",
            ip: () => "",
            is: () => "",
            is_not: () => "",
            length: () => "",
            max: (field, params) => `Максимальное количество символов ${params}.`,
            max_value: () => "",
            mimes: () => "",
            min: (field, params) => `Минимальное количество символов ${params}.`,
            min_value: () => "",
            excluded: () => "",
            numeric: (params) => `Разрешены только числовые значения`,
            regex: () => "",
            required_if: () => "",
            size: () => "",
            url: () => "",
        }
    },
    ua: {
        messages: {
            required: () => "Обязательное поле.",
            after: () => "",
            alpha_dash: () => "",
            alpha_num: () => "",
            alpha_spaces: () => "",
            before: () => "",
            between: () => "",
            confirmed: () => "",
            credit_card: () => "",
            date_between: () => "",
            date_format: () => "",
            decimal: () => "",
            digits: () => "",
            dimensions: () => "",
            email: () => "",
            ext: () => "",
            image: () => "",
            included: () => "",
            integer: () => "",
            ip: () => "",
            is: () => "",
            is_not: () => "",
            length: () => "",
            max: () => "",
            max_value: () => "",
            mimes: () => "",
            min: () => "",
            min_value: () => "",
            excluded: () => "",
            numeric: () => "",
            regex: () => "",
            required_if: () => "",
            size: () => "",
            url: () => "",
        }
    }
};
